version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www/html
      - node_modules_volume:/var/www/html/node_modules
      - build_volume:/var/www/html/public/build
    environment:
      - APP_ENV=production
      - ASSET_URL=/
    depends_on:
      - db
    networks:
      - laravel

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: node_builder
    volumes:
      - .:/app
      - node_modules_volume:/app/node_modules
      - build_volume:/app/public/build
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - build_volume:/var/www/html/public/build
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - node
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: naval
      MYSQL_USER: sebas
      MYSQL_PASSWORD: sebas123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  db_data:
  node_modules_volume:
  build_volume: